version: 2.1
jobs:
  node-build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: instalar dependencias
          command: |
            npm install
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  node-test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: pruebas
          command: |
            npm test
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - run:
          name: consola
          command: cat junit.xml
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit

  docker-build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: jjenano/tarea9
          tag: "latest,$CIRCLE_SHA1"
      - docker/push:
          image: jjenano/tarea9
          tag: "latest,$CIRCLE_SHA1"
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
            echo "hello world!!!"
  aws-deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install ecs-deploy
      - run:
          name: Deploy
          command: |
            ecs deploy $ECS_CLUSTER_NAME $ECS_SERVICE --image website-service trambocloud/nginx:$CIRCLE_SHA1 --timeout 1200 --ignore-warnings --region $AWS_REGION
orbs:
  docker: circleci/docker@1.4.0
workflows:
  version: 2
  standard-node:
    jobs:
      - node-build
      - node-test:
          requires:
            - node-build
      - docker-build-and-push:
          requires:
            - node-test
          filters:
            branches:
              only:
                - master
      - aws-deploy:
          type: approval
          requires:
            - docker-build-and-push
          filters:
            branches:
              only:
                - master
